language: c
compiler:
 - clang
 - gcc

dist: trusty
sudo: required

before_install:
 - sudo apt-get update -q
 - sudo apt-get install -y pkg-config
 - wget https://github.com/cryb-to/cryb-to/releases/download/0.20170322/cryb-to_0.20170322-1_amd64.deb
 - sudo dpkg -i cryb-to_0.20170322-1_amd64.deb

before_script:
 - ./autogen.sh
 - ./configure --enable-developer-warnings --enable-werror

script:
 - make check
